version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: hermanas_caradonti_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: hermanas2025
      MONGO_INITDB_DATABASE: hermanas_caradonti
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - hermanas_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hermanas_caradonti_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:hermanas2025@mongodb:27017/hermanas_caradonti?authSource=admin
      - JWT_SECRET_KEY=hermanas-caradonti-production-secret-key-change-me
      - ENVIRONMENT=production
      - DEBUG=false
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - hermanas_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hermanas_caradonti_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hermanas_network

volumes:
  mongodb_data:
    driver: local

networks:
  hermanas_network:
    driver: bridge